class UsageError(Exception):
    ...
class UnknownCommandError(Exception):
    ...
class NotARepoError(Exception):
    ...
class AlreadyARepoError(Exception):
    ...
class ImplementationAlreadyExistsError(Exception):
    ...
class CryptographyNotInstalledError(Exception):
    ...
class ResourceNotFoundError(Exception):
    ...